### ISSUE TITLE
Auto-discover metadata files

### ISSUE THREAD

**Issue by dtuite** [RoadieHQ/backstage-entity-validator#28]
## Describe Request:

Instead of requiring users to manually specify the list of Backstage YAML files, we should check all YAML files for `apiVersion: backstage.io/v1alpha1` and syntax check them if they have changed.

This would make it easier to automatically lint Backstage metadata files when running the validator as a hosted check solution.

**Comment by dtuite** [comment]
@kissmikijr could you close this issue if the work is complete please? GitHub and Shortcut are not kept in sync unfortunately.

**Comment by kissmikijr** [comment]
@dtuite I'd close this issue since we decided that this feature gets the most value if we put it into the github app. So the opensource validator package did not get updated by this feature. However it wouldn't be that hard to add it here also to walk the directory structure and do the validations if we want. Wdyt?

**Comment by dtuite** [comment]
Let's see how it goes on Roadie first. We can add the functionality here too if it works out well.

You can leave this issue open for now.

**Comment by marcus-crane** [comment]
One alternative, which is what I've opted to do, is just use grep to find catalogue yaml files and pipe them into the entity validator.

```
grep -rnwl -e 'apiVersion: backstage.io' --include '*.yaml' | xargs -rt validate-entity -q
```

![CleanShot 2022-04-28 at 23 32 49@2x](https://user-images.githubusercontent.com/14816406/165743287-8246cc42-3b07-42ba-bdea-32f4452518d3.png)

**Comment by dtuite** [comment]
That's a good way to accomplish this. I will close this since there's no need to build this functionality into the validator itself.
