### ISSUE TITLE
No such file or directory error during CI build

### ISSUE THREAD

**Issue by awanlin** [RoadieHQ/backstage-entity-validator#35]
## Version:

Version 0.3.8

## What happened:

We are trying to use the entity validator in an Azure DevOps build and are hitting this error:

`/usr/bin/env: 'node\r': No such file or directory`

The call we are making is: `validate-entity 'catalog/**/*.yaml' -q`

We store all our catalog entities as subfolders under `catalog`. This works fine on a local machine but fails as soon as it runs in the CI.

## Expected behavior:

It should validate the entities without error.

## Additional Information:

I'm honestly just looking for some advice as to what we might be doing wrong. Thanks for making this tool!

**Comment by awanlin** [comment]
@kissmikijr thanks for working on this, much appreciated! Looking at the linked PR it seems that it might not be an issue on our side? If that's the case when would you have a new version published?

**Comment by kissmikijr** [comment]
@awanlin Yes, it was on our side, I just published a new version of this package @roadiehq/backstage-entity-validator@0.3.9
If you update to this one it should be able to run without this issue on CI also.

**Comment by kissmikijr** [comment]
I accidentally closed it, sorry!:) If you could check and get back to this that it got solved I'd appreciate it!

**Comment by awanlin** [comment]
Just tested version 0.3.9 and that resolved the errors, this is awesome! Thanks again for working on this so quickly! I ❤️ Roadie

**Comment by kissmikijr** [comment]
Awesome, I'll close this issue.

We ❤️ our users!
