### ISSUE TITLE
[Question] Entity validator source

### ISSUE THREAD

**Issue by marcus-crane** [RoadieHQ/backstage-entity-validator#44]
Hi there,

I was having a look at the entity validator and I notice that it points to a library hosted on NPM here: https://www.npmjs.com/package/@roadiehq/roadie-backstage-entity-validator

The actual source code doesn't seem to be available from what I can tell though unless I'm missing something?

I can understand that RoadieHQ may want to keep it closed source as it's useful for their business but just wanted to confirm that I haven't overlooked another repo 🙂 

Thanks!

**Comment by kissmikijr** [comment]
Hi!
This is not the case at all! It is open-source it lives inside our plugins repo: https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/utils/roadie-backstage-entity-validator

I'll update the @roadiehq/roadie-backstage-entity-validator package to have the correct links in npm.

Thanks for this!
