### ISSUE TITLE
Update action to use Node 16

### ISSUE THREAD

**Issue by jsatt** [RoadieHQ/backstage-entity-validator#49]
## Describe Request:
Github has announced they will be deprecation of Node 12 in actions and recommending upgrading to use Node 16. Using this action currently results in the following warning.

`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16`

## Supporting Documentation Links:

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by kissmikijr** [comment]
Thank you for raising this issue. We'll make sure to bump this to node 16!
