### ISSUE TITLE
Support System, Domain and the v1beta2 templates

### ISSUE THREAD

**Issue by dtuite** [RoadieHQ/backstage-entity-validator#8]
System, Domain and the v1beta2 template kinds should be validated.

They currently don't exist in the list: https://github.com/RoadieHQ/backstage-entity-validator/blob/b92b6ebcd2e49abd9d7050e7e7a2c6b4a75812b1/src/validator.js#L24

**Comment by kissmikijr** [comment]
Released a new version (0.3.8) which contains fixes for this: https://www.npmjs.com/package/@roadiehq/backstage-entity-validator
I'm gonna close this issue,
